#!/bin/bash 
# --------------------------------------------------------------------------
# Copyright 2002-2011, OpenNebula Project Leads (OpenNebula.org)
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# --------------------------------------------------------------------------


SCRIPTS_DIR=$(dirname $0)
source $SCRIPTS_DIR/scripts_common.sh

test -f $1 || exit 1

DISK=$(to_disk $1)

DEST_DIR=$(dirname $DISK)/mnt

# Mount
mkdir -p $DEST_DIR
offset=$(fdisk -lu $DISK 2>/dev/null|grep ${DISK}1|awk '{print $2*512}')
sudo mount -o loop,offset=$offset $DISK $DEST_DIR

detect_and_init_distro

# Umount
sync
umount $DEST_DIR

echo $DISK