#!/bin/bash 
# --------------------------------------------------------------------------
# Copyright 2002-2011, OpenNebula Project Leads (OpenNebula.org)
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# --------------------------------------------------------------------------

DOWNLOAD_DIR=$1
AMI_ID=$2
CREDENTIALS=$3

source $CREDENTIALS
source $(dirname $0)/ec2.rc


IMAGES=`ec2-describe-images -K $EC2_PRIVATE_KEY -C $EC2_CERT`

exit_code=$?

if [ "$exit_code" != "0" ]; then
    exit $exit_code
fi

EC2_LOCATION=$(echo "$IMAGES" | awk "{if (\$2 == \"$AMI_ID\" ){print \$3}}")

EC2_BUCKET=`dirname $EC2_LOCATION`
EC2_MANIFEST=`basename $EC2_LOCATION`
EC2_PREFIX=${EC2_MANIFEST%.manifest.xml}

#ec2-download-bundle -b $EC2_BUCKET -p $EC2_PREFIX -d $DOWNLOAD_DIR -a $EC2_ACCESS_KEY -s $EC2_SECRET_ACCESS_KEY -k $EC2_PRIVATE_KEY 1>&2
#ec2-unbundle -k $EC2_PRIVATE_KEY -m "$DOWNLOAD_DIR/$EC2_MANIFEST" -s $DOWNLOAD_DIR -d $DOWNLOAD_DIR 1>&2

echo $1/$EC2_PREFIX