#!/bin/bash 
# --------------------------------------------------------------------------
# Copyright 2002-2011, OpenNebula Project Leads (OpenNebula.org)
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# --------------------------------------------------------------------------

CATALOG=$1
CREDENTIALS=$2

source $CREDENTIALS
source $(dirname $0)/ec2.rc

IMAGES=`ec2-describe-images -K $EC2_PRIVATE_KEY -C $EC2_CERT`

exit_code=$?

if [ "$exit_code" != "0" ]; then
    exit $exit_code
fi

echo "$IMAGES" | awk -v catalog="$CATALOG" -F'\t' 'OFS="," { if ($1 == "IMAGE") {print catalog,$2, $3} }'